"""
Qwen Code Auto-Processor

Automatically invokes Qwen Code to process action files in the Needs_Action folder.
This script bridges the gap between the watcher and Qwen Code.
"""

import subprocess
import sys
import time
import logging
import os
from pathlib import Path
from datetime import datetime
from typing import Optional


class QwenCodeProcessor:
    """
    Handles automatic invocation of Qwen Code for processing action files.
    """
    
    def __init__(self, vault_path: str):
        """
        Initialize the Qwen Code processor.
        
        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path)
        self.needs_action = self.vault_path / 'Needs_Action'
        self.in_progress = self.vault_path / 'In_Progress'
        self.done = self.vault_path / 'Done'
        self.logs = self.vault_path / 'Logs'
        self.qwen_prompt = self.vault_path / '.qwen_prompt.md'
        self.processing_flag = self.vault_path / '.qwen_processing.lock'
        
        # Ensure directories exist
        for dir_path in [self.needs_action, self.in_progress, self.done, self.logs]:
            dir_path.mkdir(parents=True, exist_ok=True)
        
        # Setup logging
        self._setup_logging()
        
        # Processing settings
        self.last_processed_count = 0
        self.last_check_time = datetime.now()
        
    def _setup_logging(self) -> None:
        """Setup logging configuration."""
        self.logger = logging.getLogger('QwenCodeProcessor')
        self.logger.setLevel(logging.INFO)
        
        # File handler
        log_file = self.logs / f'qwen_processor_{datetime.now().strftime("%Y%m%d")}.log'
        file_handler = logging.FileHandler(log_file)
        file_handler.setLevel(logging.DEBUG)
        
        # Console handler
        console_handler = logging.StreamHandler(sys.stdout)
        console_handler.setLevel(logging.INFO)
        
        # Formatter
        formatter = logging.Formatter(
            '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        )
        file_handler.setFormatter(formatter)
        console_handler.setFormatter(formatter)
        
        if not self.logger.handlers:
            self.logger.addHandler(file_handler)
            self.logger.addHandler(console_handler)
    
    def count_action_files(self) -> int:
        """Count action files in Needs_Action folder."""
        if not self.needs_action.exists():
            return 0
        return len(list(self.needs_action.glob('*.md')))
    
    def is_qwen_running(self) -> bool:
        """Check if Qwen Code is currently processing."""
        return self.processing_flag.exists()
    
    def set_processing_flag(self) -> None:
        """Set the processing flag to indicate Qwen is working."""
        self.processing_flag.write_text(
            f"Processing started: {datetime.now().isoformat()}\n"
            f"Files to process: {self.count_action_files()}"
        )
    
    def clear_processing_flag(self) -> None:
        """Clear the processing flag."""
        if self.processing_flag.exists():
            self.processing_flag.unlink()
    
    def create_qwen_prompt(self, action_count: int) -> bool:
        """
        Create a prompt file for Qwen Code to process.
        
        Args:
            action_count: Number of action files to process
            
        Returns:
            True if prompt created successfully
        """
        prompt_content = f"""---
created: {datetime.now().isoformat()}
action_count: {action_count}
status: pending
---

# AI Employee Task - Process Action Files

**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Files to Process:** {action_count}

## Instructions

You are the AI Employee. Process all files in the /Needs_Action folder.

### For Each Action File:

1. **READ** the action file carefully
2. **UNDERSTAND** what needs to be done
3. **CREATE** a Plan.md with specific steps
4. **EXECUTE** each step using available tools
5. **MOVE** the completed file to /Done folder
6. **UPDATE** Dashboard.md with the activity

### If Approval is Needed:

- Create a file in /Pending_Approval with details
- Do NOT execute until user moves file to /Approved

### Completion Signal:

When ALL files are processed and moved to /Done, output exactly:
```
<promise>TASK_COMPLETE</promise>
```

## Current Action Files

"""
        
        # List action files
        if self.needs_action.exists():
            for action_file in self.needs_action.glob('*.md'):
                prompt_content += f"- {action_file.name}\n"
        
        prompt_content += "\n---\n*Generated by QwenCodeProcessor v0.1*\n"
        
        try:
            self.qwen_prompt.write_text(prompt_content, encoding='utf-8')
            self.logger.info(f"Created Qwen prompt file with {action_count} action files")
            return True
        except Exception as e:
            self.logger.error(f"Failed to create Qwen prompt: {e}")
            return False
    
    def invoke_qwen_code(self, interactive: bool = False) -> bool:
        """
        Invoke Qwen Code to process action files.

        Args:
            interactive: If True, run in interactive mode; if False, run batch mode

        Returns:
            True if Qwen Code was invoked successfully
        """
        action_count = self.count_action_files()

        if action_count == 0:
            self.logger.info("No action files to process")
            return False

        self.logger.info(f"Found {action_count} action files, invoking Qwen Code")

        # Create the prompt
        if not self.create_qwen_prompt(action_count):
            return False

        # Set processing flag
        self.set_processing_flag()

        # Build the command
        # Qwen Code uses positional prompt: qwen "your prompt"
        # Or with -p flag: qwen -p "your prompt"
        prompt_text = f"Process all {action_count} files in ./Needs_Action folder. Create plans, execute them, and move completed files to ./Done. When all files are processed, output: <promise>TASK_COMPLETE</promise>"

        # Prepare environment with npm bin directory in PATH
        env = os.environ.copy()
        
        # Add npm global bin directory to PATH
        if sys.platform == 'win32':
            # Windows: %APPDATA%\npm
            appdata = os.environ.get('APPDATA', '')
            npm_bin_dir = str(Path(appdata) / 'npm') if appdata else None
            
            # Also check for nodejs installation
            nodejs_dir = r"C:\Program Files\nodejs"
            
            if npm_bin_dir:
                current_path = env.get('PATH', '')
                if npm_bin_dir not in current_path:
                    env['PATH'] = npm_bin_dir + os.pathsep + current_path
                    self.logger.debug(f"Added npm bin to PATH: {npm_bin_dir}")
            
            if nodejs_dir and Path(nodejs_dir).exists():
                current_path = env.get('PATH', '')
                if nodejs_dir not in current_path:
                    env['PATH'] = nodejs_dir + os.pathsep + current_path
                    self.logger.debug(f"Added nodejs to PATH: {nodejs_dir}")
        else:
            # Linux/Mac: npm bin -g
            try:
                result = subprocess.run(['npm', 'bin', '-g'], capture_output=True, text=True, shell=True)
                if result.returncode == 0:
                    npm_bin = result.stdout.strip()
                    current_path = env.get('PATH', '')
                    if npm_bin not in current_path:
                        env['PATH'] = npm_bin + os.pathsep + current_path
            except Exception:
                pass

        # Try multiple command options for Windows compatibility
        commands_to_try = []
        
        # Option 1: Direct qwen command with positional prompt and -y for auto-approve
        # Syntax: qwen "prompt text" -y
        commands_to_try.append(['qwen', prompt_text, '-y'])
        
        # Option 2: Using qwen with -p flag and -y for auto-approve
        commands_to_try.append(['qwen', '-p', prompt_text, '-y'])
        
        # Option 3: Using npx with -y for auto-approve
        commands_to_try.append(['npx', '@qwen-code/qwen-code@latest', prompt_text, '-y'])
        
        # Option 4: Using npm exec with -y for auto-approve
        commands_to_try.append(['npm', 'exec', '-y', '--package', '@qwen-code/qwen-code', '--', 'qwen', prompt_text, '-y'])

        # Try each command until one works
        for cmd in commands_to_try:
            try:
                self.logger.info(f"Trying command: {' '.join(cmd)}")

                # Run Qwen Code with enhanced PATH
                result = subprocess.run(
                    cmd,
                    cwd=str(self.vault_path),
                    capture_output=False,  # Let output go to console
                    text=True,
                    timeout=600,  # 10 minute timeout
                    shell=(sys.platform == 'win32'),  # Use shell on Windows
                    env=env  # Use enhanced environment
                )

                self.logger.info(f"Qwen Code exited with code: {result.returncode}")
                # Clear processing flag on success
                self.clear_processing_flag()
                return result.returncode == 0

            except subprocess.TimeoutExpired:
                self.logger.error("Qwen Code timed out after 10 minutes")
                continue  # Try next command
            except FileNotFoundError as e:
                self.logger.debug(f"Command not found, trying next: {e}")
                continue  # Try next command
            except Exception as e:
                self.logger.error(f"Error invoking Qwen Code: {e}")
                continue  # Try next command

        # All commands failed
        self.logger.error("Qwen Code not found! All command options failed.")
        self.logger.error("Please ensure Qwen Code is installed:")
        self.logger.error("  npm install -g @qwen-code/qwen-code")
        self.logger.error("")
        self.logger.error("Or try running with npx:")
        self.logger.error("  npx @qwen-code/qwen-code@latest")
        self.logger.error("")
        self.logger.error("If still failing, check npm bin directory is in PATH:")
        if sys.platform == 'win32':
            self.logger.error("  echo %APPDATA%\\npm")
            self.logger.error("")
            self.logger.error("To fix permanently:")
            self.logger.error("  1. Open System Properties > Environment Variables")
            self.logger.error(f"  2. Add {Path(appdata) / 'npm' if appdata else '%APPDATA%\\npm'} to PATH")
            self.logger.error("  3. Restart terminal")
        else:
            self.logger.error("  npm bin -g")
        
        # Clear processing flag
        self.clear_processing_flag()
        return False

    def process_with_ralph_loop(self, max_iterations: int = 5) -> bool:
        """
        Process files using Ralph Wiggum loop pattern.
        Keeps Qwen working until all files are processed.
        
        Args:
            max_iterations: Maximum number of Qwen invocations
            
        Returns:
            True if processing completed successfully
        """
        initial_count = self.count_action_files()
        
        if initial_count == 0:
            return False
        
        self.logger.info(f"Starting Ralph Wiggum loop with {initial_count} files")
        
        for iteration in range(max_iterations):
            remaining = self.count_action_files()
            
            if remaining == 0:
                self.logger.info("All files processed successfully!")
                return True
            
            self.logger.info(f"Iteration {iteration + 1}/{max_iterations}: {remaining} files remaining")
            
            success = self.invoke_qwen_code(interactive=False)
            
            if not success:
                self.logger.warning(f"Qwen Code invocation failed on iteration {iteration + 1}")
                # Continue anyway - might have processed some files
            
            # Small delay between iterations
            time.sleep(2)
        
        # Final check
        final_count = self.count_action_files()
        if final_count > 0:
            self.logger.warning(f"Ralph loop completed but {final_count} files still remain")
            return False
        
        return True
    
    def run_continuous(self, check_interval: int = 60) -> None:
        """
        Run continuous monitoring and processing.
        
        Args:
            check_interval: Seconds between checks (default: 60)
        """
        self.logger.info(f"Starting continuous Qwen Code processing (interval: {check_interval}s)")
        
        try:
            while True:
                action_count = self.count_action_files()
                
                if action_count > 0 and not self.is_qwen_running():
                    self.logger.info(f"Detected {action_count} action files")
                    self.process_with_ralph_loop(max_iterations=3)
                
                time.sleep(check_interval)
                
        except KeyboardInterrupt:
            self.logger.info("Continuous processing stopped by user")
        except Exception as e:
            self.logger.error(f"Error in continuous processing: {e}")
            raise


def main():
    """Entry point for the Qwen Code processor."""
    import argparse
    
    parser = argparse.ArgumentParser(description='Qwen Code Auto-Processor')
    parser.add_argument('--vault', type=str, required=True, help='Path to Obsidian vault')
    parser.add_argument('--interval', type=int, default=60, help='Check interval in seconds')
    parser.add_argument('--once', action='store_true', help='Process once and exit')
    parser.add_argument('--interactive', '-i', action='store_true', help='Interactive mode')
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose logging')
    
    args = parser.parse_args()
    
    # Setup logging
    log_level = logging.DEBUG if args.verbose else logging.INFO
    logging.basicConfig(
        level=log_level,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    )
    
    # Create processor
    processor = QwenCodeProcessor(vault_path=args.vault)
    
    if args.once:
        # Process once and exit
        success = processor.invoke_qwen_code(interactive=args.interactive)
        sys.exit(0 if success else 1)
    else:
        # Run continuous
        processor.run_continuous(check_interval=args.interval)


if __name__ == '__main__':
    main()
